Update versions and fix configuration issues

diff --git a/.github/workflows/apply.yml b/.github/workflows/apply.yml
--- a/.github/workflows/apply.yml
+++ b/.github/workflows/apply.yml
@@ -1,4 +1,3 @@
-
 name: Apply
 
 on:
@@ -15,66 +14,89 @@ permissions:
   actions: read
 
 defaults:
-    run:
-      working-directory: ./terraform
+  run:
+    working-directory: ./terraform
 
 jobs:
   terraform:
-    name: 'Terraform'
+    name: "Terraform"
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
-    
-    - name: Setup Terraform
-      uses: hashicorp/setup-terraform@v3
-      with: 
-        terraform_version: "1.9.5" 
-    
-    - name: Configure AWS credentials
-      uses: aws-actions/configure-aws-credentials@v4
-      with:
-        role-to-assume: '${{ secrets.ROLE_ARN }}'
-        role-session-name: github-actions-session
-        aws-region: eu-west-2
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - name: Terraform validate
-      run: |
-        terraform init
-        terraform fmt -check
-        terraform validate
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+        with:
+          terraform_version: "1.12.2"
 
-    - name: Linting 
-      uses: terraform-linters/setup-tflint@v4
-    - run: |
-       tflint --init
-       tflint
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: "${{ secrets.ROLE_ARN }}"
+          role-session-name: github-actions-session
+          aws-region: eu-west-2
 
-    - name: Checkov Scan
-      id: checkov
-      uses: bridgecrewio/checkov-action@v12
-      with: 
-        directory: ./terraform
-        check: CKV_AWS_1,CKV_AWS_2,CKV_AWS_41
-        soft_fail: true
+      - name: Terraform validate
+        run: |
+          terraform init
+          terraform fmt -check
+          terraform validate
 
-    - name: Terraform Apply
-      run: |
+      - name: Linting
+        uses: terraform-linters/setup-tflint@v4
+      - run: |
+          tflint --init
+          tflint
+
+      - name: Checkov Scan
+        id: checkov
+        uses: bridgecrewio/checkov-action@v12
+        with:
+          directory: ./terraform
+          check: CKV_AWS_1,CKV_AWS_2,CKV_AWS_41
+          soft_fail: true
+
+      - name: Terraform Apply
+        run: |
           terraform plan
           terraform apply -auto-approve
-    
-    - name: Wait for EKS Cluster 
-      run: |
-          aws eks wait cluster-active --name eks-cluster --region eu-west-2
-  
-    - name: Setup kubectl
-      uses: azure/setup-kubectl@v3
-      with:
-        version: 'latest'
 
-    - name: Update kubeconfig
-      run: |
-        aws eks update-kubeconfig --region eu-west-2 --name eks-cluster
-        kubectl wait --for=condition=Ready nodes --all --timeout=300s
-        kubectl apply -f ./cert-man/issuer.yaml
+      - name: Wait for EKS Cluster
+        run: |
+          aws eks wait cluster-active --name eks-cluster --region eu-west-2
+
+  argo-deploy:
+    name: Argo Deploy
+    runs-on: ubuntu-latest
+    needs: terraform
+    steps:
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: "${{ secrets.ROLE_ARN }}"
+          role-session-name: github-actions-session
+          aws-region: eu-west-2
+
+      - name: Setup kubectl
+        uses: azure/setup-kubectl@v3
+        with:
+          version: "latest"
+
+      - name: Update kubeconfig
+        run: |
+          aws eks update-kubeconfig --region eu-west-2 --name eks-cluster
+          kubectl wait --for=condition=Ready nodes --all --timeout=300s
+
+      - name: Update kubeconfig
+        run: kubectl apply -f ./cert-man/issuer.yaml
+
+      - name: Apply application
+        run: kubectl apply -f argo-cd.yaml
+
+      - name: Deploy application
+        run: kubectl apply -f manifests/deployment.yaml
+
+      - name: Decode password
+        run: kubectl -n argo-cd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d || echo "Secret not found"
